**Artificial Inteligence (CS550)**
<br>
Date: **29 January 2020**
<br>
Location: **SU, NEW STEM building**
<br>
Room: **304**

Title: **Seminar №2**
<br>
Speaker: **Dr. Shota Tsiskaridze**

In [ ]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

<h3 align="center">Basics</h3>

In [1]:
import numpy as np

In [2]:
# how to define identity matrix
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#Let's define matrices A and B, and scalar alpha

A = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
B = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
alpha = 10

A, B, alpha

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]), array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]), 10)

In [24]:
# we can sum two matries
A + B

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [25]:
# multiply A on alpha

alpha * A

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [26]:
#multiply A on B
A @ B

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [30]:
# define random matrices C
C = np.random.random(size=(3, 3))
C

array([[0.94591042, 0.08649964, 0.53762974],
       [0.86489987, 0.72747787, 0.38343153],
       [0.71207434, 0.54730433, 0.75737634]])

In [31]:
# calculate the invrese of C
invC = np.linalg.inv(C)
invC

array([[ 1.28425777,  0.86114308, -1.34760558],
       [-1.43824695,  1.25585991,  0.38515601],
       [-0.1681175 , -1.71715881,  2.30902089]])

In [32]:
# validate the inversion
I = invC @ C
np.round(I)

array([[ 1., -0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [120]:
# calculate A matrix determinant

A = np.random.random(size=(3, 3))
detA = np.linalg.det(A)
detA

-0.44260634026305207

In [122]:
# perform the eigenvalue decomposition

A = np.random.random(size=(3, 3))
A

array([[0.05320381, 0.47885094, 0.87906641],
       [0.97329283, 0.9441543 , 0.77899895],
       [0.98969944, 0.24469809, 0.78958181]])

In [123]:
eVal, eVec = np.linalg.eig(A)
Q = eVec
L = np.diag(eVal)          # remember that L is a vector of eigenvalues
Q_T = eVec.T
Q, L, Q_T

(array([[-0.41527766, -0.81785971,  0.04552174],
        [-0.76067446,  0.24491543, -0.86847113],
        [-0.49891766,  0.5206937 ,  0.49364528]]),
 array([[ 1.98644394,  0.        ,  0.        ],
        [ 0.        , -0.64985361,  0.        ],
        [ 0.        ,  0.        ,  0.45034958]]),
 array([[-0.41527766, -0.76067446, -0.49891766],
        [-0.81785971,  0.24491543,  0.5206937 ],
        [ 0.04552174, -0.86847113,  0.49364528]]))

In [124]:
# create lambda matrix
np.diag(L)

array([ 1.98644394, -0.64985361,  0.45034958])

In [125]:
A, Q_T @ L @ Q

(array([[0.05320381, 0.47885094, 0.87906641],
        [0.97329283, 0.9441543 , 0.77899895],
        [0.98969944, 0.24469809, 0.78958181]]),
 array([[ 0.07865179,  0.67874859, -0.57777668],
        [ 0.67874859,  1.41184053,  0.180026  ],
        [-0.57777668,  0.180026  , -0.37628685]]))

In [126]:
# perfomr Singular Value Decomposition

A = np.random.random(size=(2, 4))
U, S, V_T = np.linalg.svd(A)
U = np.round(U, 2)
S = np.round(S, 2)
V_T = np.round(V_T, 2)
U, S, V_T, U.shape, S.shape, V_T.shape

(array([[-0.62, -0.79],
        [-0.79,  0.62]]),
 array([1.57, 0.24]),
 array([[-0.49, -0.29, -0.15, -0.81],
        [ 0.85, -0.12,  0.11, -0.5 ],
        [-0.17,  0.01,  0.98, -0.08],
        [ 0.03, -0.95,  0.04,  0.31]]),
 (2, 2),
 (2,),
 (4, 4))